/* eslint-disable @typescript-eslint/no-explicit-any */
'use client';

import { useCallback, useMemo } from 'react';
import { warehouseConfig } from '@/config/warehouse-content';
import { useLanguage } from '@/context/LanguageContext';

// Spanish translations for warehouseConfig
const spanishTranslations: any = {
  banner: {
    title: "NUEVA NAVE INDUSTRIAL CLASE A EN RENTA",
    subtitle: "Ubicación estratégica para operaciones logísticas y de última milla",
    description: "Presentamos uno de los desarrollos industriales más atractivos en Tlalnepantla: una nave de distribución Clase A estratégicamente ubicada en el altamente demandado submercado Tlalnepantla, epicentro de logística, e-commerce, transporte y entregas de última milla para la Ciudad de México y toda el Área Metropolitana.",
    ctaText: "Agenda un Recorrido",
    ctaLink: "#contact",
  },
  warehouseFeatures: {
    title: "Características Clave del Edificio",
    subtitle: "Especificaciones Clase \"A\"",
    features: [
      {
        label: "Área del Sitio",
        value: "9,791 m²",
        icon: "area",
      },
      {
        label: "Área Total Arrendable",
        value: "7,390 m²",
        icon: "rentable",
      },
      {
        label: "Área de Almacén",
        value: "6,590 m²",
        icon: "warehouse",
      },
      {
        label: "Mezzanine",
        value: "800 m²",
        description: "Ideal para oficinas o crecimiento operativo",
        icon: "mezzanine",
      },
      {
        label: "Altura Libre",
        value: "11.0 m",
        icon: "height",
      },
      {
        label: "Espaciado de Columnas",
        value: "12 × 24 m",
        description: "Óptimo para estanterías y maniobras internas",
        icon: "spacing",
      },
    ],
  },
  locations: {
    title: "Ubicación Estratégica Privilegiada",
    subtitle: "Acceso directo y eficiente a las principales zonas industriales",
    highlights: [
      "Ciudad de México",
      "Autopista México–Querétaro (57)",
      "Zona Industrial Vallejo",
      "San Martín Obispo",
      "Circuito Exterior Mexiquense",
      "Submercados industriales Cuautitlán–Tultitlán–Tepotzotlán",
      "Principales centros logísticos e industriales del norte del Valle de México",
    ],
    description: "Esta área es una de las zonas logísticas más consolidadas y demandadas del país, con niveles de desocupación extremadamente bajos y una ubicación privilegiada para distribución urbana.",
    addresses: [
      {
        name: "Almacén Tlalnepantla",
        address: "Avenida Prolongación Hidalgo No.3, Col. Pueblo San Pedro Barrientos, Municipio Tlalnepantla De Baez, Edo. De México, C.P. 54010",
        mapLink: "https://maps.app.goo.gl/mgj6YRcikX8zeznC8",
        usps: [
          " Ubicación infill premium con acceso inmediato a los mercados de consumo y fuerza laboral más robustos de la Ciudad de México",
          "Ideal para operaciones de última milla gracias a su proximidad inigualable con CDMX",
          "Acceso directo a carreteras principales como Gustavo Baz y Periférico Norte",
          "Perfecto para e-commerce, cadenas de retail y logística urbana",
        ],
        idealFor: [
          "Logística y distribución metropolitana",
          "Operaciones de última milla y comercio electrónico",
          "Courier, paquetería y mensajería exprés",
          "Centros de cross-dock y consolidación",
          "Manufactura ligera",
        ],
      },
    ],
  },
  specifications: {
    title: "Especificaciones del Almacén",
    subtitle: "Características constructivas de clase mundial para una eficiencia operativa excepcional",
    tabs: [
      {
        id: "building",
        label: "Características del Edificio",
        items: [
          "Altura libre: 11.0 m",
          "Separación entre columnas: 12 × 24 m",
          " Muros: Concreto reforzado y panel metálico aislado",
          " Techo: Panel KR-18 con aislamiento termoacústico",
          "Iluminación natural: 10%",
          "Iluminación artificial: Luminarias LED",
        ],
      },
      {
        id: "infrastructure",
        label: "Infraestructura",
        items: [
          "Estacionamientos",
          "Andenes de carga",
          " Oficinas (mezanine de 800 m²)",
          "Suministro eléctrico",
          "Sistema contra incendios",
          "Sistema de pararrayos",
        ],
      },
      {
        id: "security",
        label: "Seguridad y Protección",
        items: [
          "Seguridad 24/7",
          "Videovigilancia CCTV",
          "Caseta de acceso controlado",
          "Protección contra incendios: hidrantes, mangueras y gabinetes",
        ],
      },
      {
        id: "operational",
        label: "Características Operativas",
        items: [
          "Acceso 24x7",
          "Sistemas automatizados",
          "Alturas libres de 11 m",
          "Compatibilidad para racks",
          "Andenes de carga",
          " Capacidades de cross-dock",
        ],
      },
    ],
  },
  targetIndustries: {
    title: "Ideal Para",
    subtitle: "Perfecto para diversas operaciones industriales y logísticas",
    industries: [
      {
        id: "ecommerce",
        name: "Comercio Electrónico",
        description: "Centros de cumplimiento y distribución de última milla",
      },
      {
        id: "logistics",
        name: "Logística y Distribución",
        description: "3PL, servicios de mensajería y paquetería",
      },
      {
        id: "retail",
        name: "Cadena de Suministro Minorista",
        description: "Minoristas y distribución de bienes de consumo rápido",
      },
      {
        id: "manufacturing",
        name: "Manufactura",
        description: "Manufactura ligera y ensamblaje",
      },
      {
        id: "pharma",
        name: "Farmacéutico",
        description: "Distribución y almacenamiento farmacéutico",
      },
      {
        id: "automotive",
        name: "Automotriz",
        description: "Piezas y componentes automotrices",
      },
    ],
  },
  availability: {
    status: "INMEDIATO",
    statusText: "Cronograma perfecto para la planeación operativa y la adecuación del espacio",
    pricing: "Contactar para precios",
    pricingModel: "Términos de Renta",
    leaseTerms: "Contrato mínimo de 36 meses",
  },
  ctas: {
    primary: {
      text: "Agenda un Recorrido",
      link: "#contact",
    },
    secondary: {
      text: "Programar Llamada",
      link: "#contact",
    },
    whatsapp: {
      text: "Contactar vía WhatsApp",
      link: "https://wa.me/525512345678",
    },
    download: {
      text: "Descargar Folleto",
      link: "/brochure.pdf",
    },
  },
  leadForm: {
    title: "Póngase en Contacto",
    subtitle: "Completa el formulario y nos pondremos en contacto contigo.",
    fields: [
      { name: "fullName", label: "Nombre Completo", type: "text", required: true },
      { name: "companyName", label: "Nombre de la Empresa", type: "text", required: true },
      { name: "phone", label: "Número de Teléfono", type: "tel", required: true },
      { name: "email", label: "Correo Electrónico", type: "email", required: true },
      { name: "warehouseSize", label: "Requerimientos de superficie", type: "text", required: false },
      { name: "preferredLocation", label: "Ubicación Preferida", type: "select", options: ["Tlalnepantla", "Jilotepec", "Ambos"], required: false },
      { name: "budget", label: "Presupuesto", type: "text", required: false },
      { name: "leaseDuration", label: "Duración del contrato de renta", type: "text", required: false },
      { name: "timeline", label: "Fecha estimada de ocupación", type: "text", required: false },
      { name: "additionalNotes", label: "Notas Adicionales", type: "textarea", required: false },
    ],
  },
  disclaimer: "Esta información ha sido preparada por Jilotepec Logistics únicamente con fines informativos. Jilotepec Logistics no otorga garantías ni realiza declaraciones de ningún tipo, expresas o implícitas, respecto a la información contenida, incluyendo, entre otras, garantías sobre su contenido, exactitud y confiabilidad. Cualquier parte interesada deberá realizar su propia investigación para verificar la exactitud de la información. Jilotepec Logistics excluye de manera inequívoca todos los términos, condiciones y garantías inferidos o implícitos que pudieran derivarse de este documento, y excluye toda responsabilidad por pérdidas o daños que pudieran surgir del mismo.",
};

// Additional UI translations
const uiTranslations: Record<string, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.connectivity': 'Connectivity',
    'nav.specifications': 'Specifications',
    'nav.infrastructure': 'Infrastructure',
    'nav.opportunities': 'Opportunities',
    'nav.applications': 'Applications',
    'nav.callNow': 'Call Now',
    'banner.badge': 'Industrial Warehouse for Lease',
    'banner.title': 'Jilotepec Logistics Center',
    'banner.subtitle': 'Premier Location at the Intersection Of Arco Norte & Highway 57',
    'banner.description': "Position your logistics or manufacturing operation in one of Mexico's most strategic industrial hubs: JILOTEPEC LOGISTICS CENTER, a world-class industrial park located at the exact crossroads of Arco Norte and Highway 57 (Mexico–Querétaro).",
    'banner.cta': 'Schedule a Tour',
    'banner.feature1Title': 'Premier Location',
    'banner.feature1Desc': "Strategic position at Mexico's key logistics intersection",
    'banner.feature2Title': 'Distribution Hub',
    'banner.feature2Desc': 'Unmatched national and regional connectivity',
    'banner.feature3Title': 'Premium Infrastructure',
    'banner.feature3Desc': 'High-capacity utilities and robust systems',
    'banner.feature4Title': 'Advanced Security',
    'banner.feature4Desc': 'State-of-the-art security and surveillance systems',
    'banner.availableOptions': 'Available Options',
    'banner.leaseSaleBuild': 'Lease, Sale & Build-to-Suit',
    'banner.facilityType': 'Facility Type',
    'banner.largeScaleWarehouses': 'Large-Scale Warehouses',
    'strategic.badge': 'Strategic Location Benefits',
    'strategic.title': "Mexico's Most Efficient Logistics Node",
    'strategic.subtitle': "CLJ is positioned in one of the most efficient logistics nodes in the country, connecting instantly with Mexico's key corridors.",
    'strategic.directHighwayAccess': 'Direct Highway Access',
    'strategic.route1Title': 'Highway 57D',
    'strategic.route1Desc': 'Mexico–Querétaro–San Luis Potosí corridor',
    'strategic.route2Title': 'Arco Norte 40D',
    'strategic.route2Desc': 'Bajío–Gulf–Central–Puebla–Tlaxcala link',
    'strategic.route3Title': 'Circuito Exterior',
    'strategic.route3Desc': 'Mexiquense ring road system',
    'strategic.route4Title': 'Rapid Access',
    'strategic.route4Desc': 'Mexico City, Bajío, Pacific, Gulf & Northern routes',
    'strategic.stat1': 'Consumers in Greater Mexico City',
    'strategic.stat2': 'Major Regions Connected',
    'strategic.stat3': 'Efficient Distribution Network',
    'strategic.keyAdvantages': 'Key Operational Advantages',
    'strategic.adv1Title': 'Efficient Distribution',
    'strategic.adv1Desc': 'Highly efficient distribution to ports, borders, and major consumption markets',
    'strategic.adv2Title': 'Reduced Transit Times',
    'strategic.adv2Desc': 'Minimized delivery times for national and regional distribution routes',
    'strategic.adv3Title': 'Market Reach',
    'strategic.adv3Desc': 'Immediate access to 23+ million consumers in the metro area',
    'strategic.adv4Title': 'Strategic Positioning',
    'strategic.adv4Desc': 'Perfect positioning for supply chains connecting north–central–south',
    'strategic.adv5Title': 'Versatile Operations',
    'strategic.adv5Desc': 'Ideal for 3PLs, retail distribution, e-commerce, and manufacturing',
    'strategic.adv6Title': 'Multi-Region Coverage',
    'strategic.adv6Desc': 'Direct connectivity to Bajío, Gulf, Central, Puebla, and Tlaxcala regions',
    'locationComparison.title': 'Choose Your Ideal Location',
    'locationComparison.subtitle': 'A strategic location, optimized for operational efficiency. Discover how it can perfectly support your business needs.',
    'locationComparison.keyAdvantages': 'Key Advantages',
    'locationComparison.idealFor': 'Ideal For',
    'locationComparison.openInMaps': 'Open in Google Maps',
    'locations.strategicAccessPoints': 'Strategic Access Points',
    'gallery.title': 'Gallery',
    'gallery.subtitle': 'Explore our state-of-the-art warehouse facilities through our photo and video gallery. See the quality and features that make our spaces ideal for your operations.',
    'availability.title': 'Availability & Pricing',
    'availability.subtitle': 'Ready to move in immediately. Flexible pricing options to suit your business needs.',
    'availability.leaseTerms': 'Lease Terms',
    'availability.getQuote': 'Get Quote',
    'availability.contactUs': 'Contact Us',
    'cta.title': 'Ready to Get Started?',
    'cta.subtitle': 'Explore our Class A warehouse facilities and discover how we can support your business operations.',
    'cta.warehouseTitle': 'Modern Warehouse Solutions',
    'cta.warehouseDesc': 'Streamline your logistics, optimize inventory management, and scale your operations with our cutting-edge warehouse technology',
    'cta.getStartedToday': 'Get Started Today',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Choose your preferred method to contact us. We are here to help you find the perfect warehouse solution.',
    'contact.whatsapp': 'WhatsApp',
    'contact.chatWithUs': 'Chat with us instantly',
    'contact.callUs': 'Call Us',
    'contact.contactUs': 'Contact Us',
    'form.submitting': 'Submitting...',
    'form.required': 'is required',
    'form.success': "✅ Thank you! We've received your inquiry and will get back to you shortly.",
    'form.formTitle': 'Warehouse Inquiry Form',
    'form.formSubtitle': 'Share your requirements and we will match you with available warehouse spaces',
    'form.contactInfo': 'Contact Information',
    'form.contactInfoDesc': 'Let us know how to reach you',
    'form.fullName': 'Full Name',
    'form.companyName': 'Company Name',
    'form.emailAddress': 'Email Address',
    'form.phoneNumber': 'Phone Number',
    'form.placeholderFullName': 'John Smith',
    'form.placeholderCompany': 'Acme Corporation',
    'form.placeholderEmail': 'john@acme.com',
    'form.placeholderPhone': '9–12 digits (numbers only)',
    'form.requiredFullName': 'Full name is required.',
    'form.invalidFullName': 'Full name can only contain letters, spaces, hyphens and apostrophes.',
    'form.requiredCompany': 'Company name is required.',
    'form.invalidCompany': 'Company name can only contain letters, spaces, hyphens and apostrophes.',
    'form.requiredEmail': 'Email is required.',
    'form.invalidEmail': 'Please enter a valid email address.',
    'form.requiredPhone': 'Phone number is required.',
    'form.invalidPhone': 'Phone must be 9–12 digits (numbers only).',
    'form.warehouseReqs': 'Warehouse Requirements',
    'form.warehouseReqsDesc': 'Tell us about your space needs',
    'form.warehouseSize': 'Warehouse Size (sq ft)',
    'form.preferredLocation': 'Preferred Location',
    'form.monthlyBudget': 'Monthly Budget',
    'form.leaseDuration': 'Lease Duration',
    'form.timelineToMoveIn': 'Timeline to Move In',
    'form.placeholderSize': '4000',
    'form.placeholderLocation': 'City, State or Region',
    'form.placeholderBudget': '200000',
    'form.placeholderLease': '5 Years',
    'form.placeholderTimeline': '1 Month',
    'form.additionalInfo': 'Additional Information',
    'form.additionalInfoDesc': 'Any special requirements or questions?',
    'form.additionalNotes': 'Additional Notes',
    'form.placeholderNotes': 'Tell us about any specific requirements: loading docks, ceiling height, temperature control, security features, etc.',
    'form.requiredFields': 'Required fields',
    'form.submitInquiry': 'Submit Inquiry',
    'form.failedSubmit': 'Failed to submit form',
    'form.errorSubmit': 'Something went wrong while submitting. Please try again.',
    'form.disclaimer': 'This information has been prepared by Jilotepec Logistics for general information only. Jilotepec Logistics makes no warranties nor representations of any kind, express or implied, with respect to the information, including, but not limited to, warranties of content, accuracy, and reliability. Any interested party should make their own inquiries about the accuracy of the information. Jilotepec Logistics unequivocally excludes all inferred or implied terms, conditions and warranties arising from this document and excludes all liability for loss and damage arising therefrom.',
    'form.toastTitle': 'Thank you for your inquiry!',
    'form.toastMessage': 'Our team will contact you within 24 hours to discuss your warehouse needs.',
    'spec.title': 'Park & Building Specifications',
    'spec.parkOverview': 'Park Overview',
    'spec.totalParkLand': 'Total Park Land',
    'spec.phase1': 'Phase 1: 33 ha',
    'spec.existingBuildings': 'Existing Buildings',
    'spec.buildingA': 'Building A',
    'spec.leased': '100% LEASED',
    'spec.buildingB': 'Building B',
    'spec.immediateAvailability': 'IMMEDIATE AVAILABILITY',
    'spec.divisibleSpace': 'Divisible Space',
    'spec.landAvailable': 'Land Available',
    'spec.forSaleOrBTS': 'For Sale or BTS Projects',
    'spec.classAFeatures': 'Class-A Building Features',
    'spec.concreteWalls': 'Concrete walls',
    'spec.kr18Roof': 'KR-18 insulated metal roof',
    'spec.naturalLighting': '6% natural lighting via polycarbonate skylights',
    'spec.clearHeight': 'Clear height: 11.50 m (38 ft)',
    'spec.concreteFloor': '6" (15 cm) concrete floor',
    'spec.dockDoors': 'Fully equipped dock doors (up to 1 dock / 350 SQM approx.)',
    'spec.driveInRamps': 'Drive-in ramps (BTS options)',
    'spec.truckCourts': '40-meter deep truck courts',
    'spec.ledLighting': 'LED lighting throughout',
    'spec.hydrantsSprinkler': 'Hydrants and sprinkler-ready system',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.ourLocations': 'Our Locations',
    'footer.disclaimer': 'Disclaimer',
    'footer.tagline': 'Premium Class A industrial warehouse facilities in strategic locations across Mexico. Your partner for logistics excellence.',
    'footer.forMoreInfo': 'For more information:',
    'footer.execManagingDirector': 'Executive Managing Director | Industrial',
    'footer.industrialBroker': 'Industrial Broker',
    'footer.mexicoCity': 'Mexico City',
    'footer.nyHeadquarters': 'New York Headquarters',
    'footer.disclaimerText': 'This document has been prepared for general informational purposes only. No warranties or representations of any kind, whether express or implied, are made with respect to the information contained herein, including, without limitation, its content, accuracy, or reliability. Any interested party should conduct its own independent investigation and verification of the information. All inferred or implied terms, conditions, and warranties arising from this document are expressly excluded, as is any liability for loss or damage arising from its use. The information contained herein is subject to change without prior notice.',
    'footer.copyright': '© 2025 Jilotepec Logistics. All rights reserved.',
    'security.title': 'ADVANCED SECURITY SYSTEMS',
    'security.subtitle': 'Each building within the park includes comprehensive security measures designed for maximum protection and operational efficiency',
    'security.doublePerimeterTitle': 'Double Perimeter Security',
    'security.doublePerimeterDesc': 'Our multi-layered security approach combines outer fencing with an internal controlled perimeter, creating a fortress-level protection system for your operations.',
    'security.doublePerimeterAlt': 'Double perimeter security system',
    'security.feature1Title': 'Outer security fencing + internal controlled perimeter',
    'security.feature1Desc': 'Multi-layer perimeter protection with advanced boundary systems',
    'security.feature2Title': '24/7 manned access control',
    'security.feature2Desc': 'Round-the-clock professional security personnel and monitoring',
    'security.feature3Title': 'Centralized monitoring and surveillance',
    'security.feature3Desc': 'State-of-the-art monitoring systems with real-time oversight',
    'security.feature4Title': 'Segregated access for trucks, vehicles, and personnel',
    'security.feature4Desc': 'Dedicated entry points ensuring optimal traffic flow and safety',
    'security.bottomCta': 'This ensures a highly controlled and secure operational environment for industrial users.',
    'infrastructure.title': 'High-Capacity Water & Power Infrastructure',
    'infrastructure.description': 'Enterprise-grade utility systems designed for high-demand industrial operations',
    'infrastructure.electricalTitle': 'Electrical Capacity',
    'infrastructure.electrical1': 'Redundant 7 MVA substation',
    'infrastructure.electrical2': '23 KV medium-voltage line',
    'infrastructure.electrical3': '140 KVA per hectare available',
    'infrastructure.electrical4': 'LED street lighting',
    'infrastructure.waterTitle': 'Water',
    'infrastructure.water1': 'Two water wells',
    'infrastructure.water2': 'Aquifer with availability for high-demand users',
    'infrastructure.water3': 'MBBR wastewater treatment plant (90 m³/day)',
    'infrastructure.servicesTitle': 'Additional Services',
    'infrastructure.services1': 'Conduits for voice and data',
    'infrastructure.services2': 'Natural gas available',
    'infrastructure.services3': 'Park administration building and service areas',
    'infrastructure.services4': 'Planned on-site fuel station',
    'bts.title': 'Land Available for Build-to-Suit Projects',
    'bts.subtitle': 'In addition to existing buildings, CLJ offers comprehensive land solutions',
    'bts.landAlt': 'Aerial view of CLJ industrial land',
    'bts.availableNow': 'Available Now',
    'bts.feature1Title': '30+ hectares',
    'bts.feature1Desc': 'Fully serviced with infrastructure at lot line',
    'bts.feature2Title': '23+ hectares',
    'bts.feature2Desc': 'Hectares of additional industrial reserve land',
    'bts.projectCapabilities': 'Project Capabilities',
    'bts.projectDesc': 'Suitable for BTS projects ranging from 10,000 m² to over 100,000 m², tailored to the exact needs of the user.',
    'locationInfo.facilityName': 'Location 2',
    'locationInfo.street': 'Manzana 057',
    'locationInfo.city': 'Jilotepec de Molina Enríquez',
    'locationInfo.state': 'Edo. De Mexico',
    'locationInfo.postalCode': 'C.P. 54250',
    'locationInfo.warehouseAddress': 'Warehouse Address',
    'locationInfo.viewOnMaps': 'View on Google Maps',
    'locationInfo.mapTitle': 'Warehouse location map',
    'idealFor.title': 'Ideal For',
    'idealFor.op1Title': 'National and Regional Distribution Centers',
    'idealFor.op1Desc': 'Large-scale operations requiring efficient logistics coordination',
    'idealFor.op2Title': 'E-commerce and Retail Fulfillment',
    'idealFor.op2Desc': 'Fast-paced order processing and delivery management',
    'idealFor.op3Title': '3PL Logistics Providers',
    'idealFor.op3Desc': 'Multi-client warehouse and transportation services',
    'idealFor.op4Title': 'Manufacturing and Assembly Operations',
    'idealFor.op4Desc': 'Production facilities with complex supply chain needs',
    'idealFor.op5Title': 'High-Demand Utility Users',
    'idealFor.op5Desc': 'Operations requiring consistent power and resources',
    'idealFor.op6Title': 'Large Corporate Supply Chain Operations',
    'idealFor.op6Desc': 'Enterprise-level logistics and distribution management',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.connectivity': 'Conectividad',
    'nav.specifications': 'Especificaciones',
    'nav.infrastructure': 'Infraestructura',
    'nav.opportunities': 'Oportunidades',
    'nav.applications': 'Aplicaciones',
    'nav.callNow': 'Llamar Ahora',
    'banner.badge': 'Almacén industrial en renta',
    'banner.title': 'Jilotepec Logistics Center',
    'banner.subtitle': 'Ubicación privilegiada en la intersección del Arco Norte y la Carretera 57',
    'banner.description': "Ubique su operación logística o manufacturera en uno de los polos industriales más estratégicos de México: JILOTEPEC LOGISTICS CENTER, un parque industrial de clase mundial ubicado en el cruce del Arco Norte y la Carretera 57 (México–Querétaro).",
    'banner.cta': 'Agendar recorrido',
    'banner.feature1Title': 'Ubicación privilegiada',
    'banner.feature1Desc': 'Posición estratégica en el cruce logístico clave de México',
    'banner.feature2Title': 'Centro de distribución',
    'banner.feature2Desc': 'Conectividad nacional y regional inigualable',
    'banner.feature3Title': 'Infraestructura premium',
    'banner.feature3Desc': 'Servicios de alta capacidad y sistemas robustos',
    'banner.feature4Title': 'Seguridad avanzada',
    'banner.feature4Desc': 'Sistemas de seguridad y videovigilancia de vanguardia',
    'banner.availableOptions': 'Opciones disponibles',
    'banner.leaseSaleBuild': 'Renta, venta y construcción a la medida',
    'banner.facilityType': 'Tipo de instalación',
    'banner.largeScaleWarehouses': 'Almacenes de gran escala',
    'strategic.badge': 'Beneficios de ubicación estratégica',
    'strategic.title': 'El nodo logístico más eficiente de México',
    'strategic.subtitle': 'CLJ está posicionado en uno de los nodos logísticos más eficientes del país, conectando al instante con los corredores clave de México.',
    'strategic.directHighwayAccess': 'Acceso directo a carreteras',
    'strategic.route1Title': 'Carretera 57D',
    'strategic.route1Desc': 'Corredor México–Querétaro–San Luis Potosí',
    'strategic.route2Title': 'Arco Norte 40D',
    'strategic.route2Desc': 'Enlace Bajío–Golfo–Centro–Puebla–Tlaxcala',
    'strategic.route3Title': 'Circuito Exterior',
    'strategic.route3Desc': 'Sistema de anillo vial mexiquense',
    'strategic.route4Title': 'Acceso rápido',
    'strategic.route4Desc': 'Rutas a Ciudad de México, Bajío, Pacífico, Golfo y Norte',
    'strategic.stat1': 'Consumidores en la Zona Metropolitana',
    'strategic.stat2': 'Regiones principales conectadas',
    'strategic.stat3': 'Red de distribución eficiente',
    'strategic.keyAdvantages': 'Ventajas operativas clave',
    'strategic.adv1Title': 'Distribución eficiente',
    'strategic.adv1Desc': 'Distribución altamente eficiente a puertos, fronteras y mercados de consumo principales',
    'strategic.adv2Title': 'Tiempos de tránsito reducidos',
    'strategic.adv2Desc': 'Tiempos de entrega minimizados para rutas de distribución nacional y regional',
    'strategic.adv3Title': 'Alcance de mercado',
    'strategic.adv3Desc': 'Acceso inmediato a más de 23 millones de consumidores en el área metropolitana',
    'strategic.adv4Title': 'Posicionamiento estratégico',
    'strategic.adv4Desc': 'Posicionamiento ideal para cadenas de suministro que conectan norte–centro–sur',
    'strategic.adv5Title': 'Operaciones versátiles',
    'strategic.adv5Desc': 'Ideal para 3PL, distribución retail, e-commerce y manufactura',
    'strategic.adv6Title': 'Cobertura multirregional',
    'strategic.adv6Desc': 'Conectividad directa con Bajío, Golfo, Centro, Puebla y Tlaxcala',
    'locationComparison.title': 'Elija Su Ubicación Ideal',
    'locationComparison.subtitle': 'Una ubicación estratégica, optimizada para la eficiencia operativa. Descubra cómo puede apoyar perfectamente las necesidades de su negocio.',
    'locationComparison.keyAdvantages': 'Ventajas Clave',
    'locationComparison.idealFor': 'Ideal Para',
    'locationComparison.openInMaps': 'Abrir en Google Maps',
    'locations.strategicAccessPoints': 'Puntos de Acceso Estratégicos',
    'gallery.title': 'Galería',
    'gallery.subtitle': 'Explora nuestras instalaciones de vanguardia a través de la galería de fotos y videos. Conoce la calidad y características que hacen que nuestros espacios sean ideales para tus operaciones.',
    'availability.title': 'Disponibilidad y Precios',
    'availability.subtitle': 'Listo para ocupar de inmediato. Opciones de precios flexibles según tus necesidades.',
    'availability.leaseTerms': 'Términos de Arrendamiento',
    'availability.getQuote': 'Obtener Cotización',
    'availability.contactUs': 'Solicita Cotización',
    'cta.title': '¿Listo para Comenzar?',
    'cta.subtitle': 'Explora nuestras naves industriales Clase A y descubre cómo podemos apoyar tus operaciones.',
    'cta.warehouseTitle': 'Soluciones de Almacén Modernas',
    'cta.warehouseDesc': 'Simplifique su logística, optimice la gestión de inventario y escale sus operaciones con nuestra tecnología de almacén de vanguardia',
    'cta.getStartedToday': 'Comience Hoy',
    'contact.title': 'Contáctenos',
    'contact.subtitle': 'Elige el método de contacto que prefieras. Estamos aquí para ayudarte a encontrar la solución de almacén perfecta.',
    'contact.whatsapp': 'WhatsApp',
    'contact.chatWithUs': 'Chatea con nosotros al instante',
    'contact.callUs': 'Llámanos',
    'contact.contactUs': 'Contáctenos',
    'form.submitting': 'Enviando...',
    'form.required': 'es requerido',
    'form.success': '✅ ¡Gracias! Hemos recibido su consulta y nos pondremos en contacto con usted pronto.',
    'form.formTitle': 'Formulario de consulta de almacén',
    'form.formSubtitle': 'Comparta sus requisitos y le pondremos en contacto con espacios de almacén disponibles',
    'form.contactInfo': 'Información de contacto',
    'form.contactInfoDesc': 'Déjenos saber cómo contactarle',
    'form.fullName': 'Nombre completo',
    'form.companyName': 'Nombre de la empresa',
    'form.emailAddress': 'Correo electrónico',
    'form.phoneNumber': 'Número de teléfono',
    'form.placeholderFullName': 'Juan Pérez',
    'form.placeholderCompany': 'Empresa S.A.',
    'form.placeholderEmail': 'juan@empresa.com',
    'form.placeholderPhone': '9–12 dígitos (solo números)',
    'form.requiredFullName': 'El nombre completo es obligatorio.',
    'form.invalidFullName': 'El nombre solo puede contener letras, espacios, guiones y apóstrofes.',
    'form.requiredCompany': 'El nombre de la empresa es obligatorio.',
    'form.invalidCompany': 'El nombre de la empresa solo puede contener letras, espacios, guiones y apóstrofes.',
    'form.requiredEmail': 'El correo electrónico es obligatorio.',
    'form.invalidEmail': 'Introduzca una dirección de correo válida.',
    'form.requiredPhone': 'El número de teléfono es obligatorio.',
    'form.invalidPhone': 'El teléfono debe tener 9–12 dígitos (solo números).',
    'form.warehouseReqs': 'Requisitos del almacén',
    'form.warehouseReqsDesc': 'Cuéntenos sus necesidades de espacio',
    'form.warehouseSize': 'Tamaño del almacén (m²)',
    'form.preferredLocation': 'Ubicación preferida',
    'form.monthlyBudget': 'Presupuesto mensual',
    'form.leaseDuration': 'Duración del arrendamiento',
    'form.timelineToMoveIn': 'Plazo para mudarse',
    'form.placeholderSize': '4000',
    'form.placeholderLocation': 'Ciudad, estado o región',
    'form.placeholderBudget': '200000',
    'form.placeholderLease': '5 años',
    'form.placeholderTimeline': '1 mes',
    'form.additionalInfo': 'Información adicional',
    'form.additionalInfoDesc': '¿Algún requisito especial o pregunta?',
    'form.additionalNotes': 'Notas adicionales',
    'form.placeholderNotes': 'Cuéntenos requisitos específicos: muelles de carga, altura del techo, control de temperatura, seguridad, etc.',
    'form.requiredFields': 'Campos obligatorios',
    'form.submitInquiry': 'Enviar consulta',
    'form.failedSubmit': 'Error al enviar el formulario',
    'form.errorSubmit': 'Algo salió mal al enviar. Por favor, inténtelo de nuevo.',
    'form.disclaimer': 'Esta información ha sido preparada por Jilotepec Logistics con fines informativos generales. Jilotepec Logistics no ofrece garantías ni declaraciones de ningún tipo, expresas o implícitas, respecto a la información, incluyendo, entre otras, garantías de contenido, exactitud y fiabilidad. Cualquier parte interesada debe realizar sus propias averiguaciones sobre la exactitud de la información. Jilotepec Logistics excluye inequívocamente todos los términos, condiciones y garantías inferidos o implícitos que surjan de este documento y excluye toda responsabilidad por pérdidas y daños que se deriven del mismo.',
    'form.toastTitle': '¡Gracias por su consulta!',
    'form.toastMessage': 'Nuestro equipo se pondrá en contacto en 24 horas para hablar de sus necesidades de almacén.',
    'spec.title': 'Especificaciones del Parque y Edificios',
    'spec.parkOverview': 'Resumen del Parque',
    'spec.totalParkLand': 'Terreno Total del Parque',
    'spec.phase1': 'Fase 1: 33 ha',
    'spec.existingBuildings': 'Edificios Existentes',
    'spec.buildingA': 'Edificio A',
    'spec.leased': '100% ARRENDADO',
    'spec.buildingB': 'Edificio B',
    'spec.immediateAvailability': 'DISPONIBILIDAD INMEDIATA',
    'spec.divisibleSpace': 'Espacio Divisible',
    'spec.landAvailable': 'Terreno Disponible',
    'spec.forSaleOrBTS': 'Venta o Proyectos BTS',
    'spec.classAFeatures': 'Características de Edificio Clase A',
    'spec.concreteWalls': 'Muros de concreto',
    'spec.kr18Roof': 'Techo metálico aislado KR-18',
    'spec.naturalLighting': '6% de iluminación natural con claraboyas de policarbonato',
    'spec.clearHeight': 'Altura libre: 11.50 m (38 ft)',
    'spec.concreteFloor': 'Piso de concreto 6" (15 cm)',
    'spec.dockDoors': 'Muelles de carga equipados (aprox. 1 muelle / 350 m²)',
    'spec.driveInRamps': 'Rampas de acceso (opciones BTS)',
    'spec.truckCourts': 'Patios de maniobras de 40 m de fondo',
    'spec.ledLighting': 'Iluminación LED en todo el edificio',
    'spec.hydrantsSprinkler': 'Hidrantes y sistema listo para rociadores',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.ourLocations': 'Nuestras Ubicaciones',
    'footer.disclaimer': 'Descargo de Responsabilidad',
    'footer.tagline': 'Instalaciones de almacenes industriales Clase A premium en ubicaciones estratégicas en México. Su socio para la excelencia logística.',
    'footer.forMoreInfo': 'Para más información:',
    'footer.execManagingDirector': 'Director General Ejecutivo | Industrial',
    'footer.industrialBroker': 'Corredor Industrial',
    'footer.mexicoCity': 'Ciudad de México',
    'footer.nyHeadquarters': 'Sede Nueva York',
    'footer.disclaimerText': 'Este documento ha sido preparado únicamente con fines informativos generales. No se otorgan garantías ni declaraciones de ningún tipo, expresas o implícitas, respecto a la información contenida en el mismo, incluyendo, sin limitación, su contenido, exactitud o confiabilidad. Cualquier parte interesada debe realizar su propia investigación y verificación independiente de la información. Se excluyen expresamente todos los términos, condiciones y garantías inferidos o implícitos que surjan de este documento, así como cualquier responsabilidad por pérdidas o daños derivados de su uso. La información contenida en el mismo está sujeta a cambios sin previo aviso.',
    'footer.copyright': '© 2025 Jilotepec Logistics. Todos los derechos reservados.',
    'security.title': 'SISTEMAS DE SEGURIDAD AVANZADOS',
    'security.subtitle': 'Cada edificio dentro del parque incluye medidas de seguridad integrales diseñadas para máxima protección y eficiencia operativa',
    'security.doublePerimeterTitle': 'Seguridad de Doble Perímetro',
    'security.doublePerimeterDesc': 'Nuestro enfoque de seguridad multicapa combina cerco perimetral externo con un perímetro interno controlado, creando un sistema de protección nivel fortaleza para sus operaciones.',
    'security.doublePerimeterAlt': 'Sistema de seguridad de doble perímetro',
    'security.feature1Title': 'Cerco perimetral externo + perímetro interno controlado',
    'security.feature1Desc': 'Protección perimetral multicapa con sistemas de límites avanzados',
    'security.feature2Title': 'Control de acceso con personal 24/7',
    'security.feature2Desc': 'Personal de seguridad profesional y monitoreo las 24 horas',
    'security.feature3Title': 'Monitoreo y vigilancia centralizados',
    'security.feature3Desc': 'Sistemas de monitoreo de vanguardia con supervisión en tiempo real',
    'security.feature4Title': 'Acceso segregado para camiones, vehículos y personal',
    'security.feature4Desc': 'Puntos de entrada dedicados que garantizan flujo de tráfico y seguridad óptimos',
    'security.bottomCta': 'Esto garantiza un entorno operativo altamente controlado y seguro para usuarios industriales.',
    'infrastructure.title': 'Infraestructura de Agua y Energía de Alta Capacidad',
    'infrastructure.description': 'Sistemas de servicios de nivel empresarial diseñados para operaciones industriales de alta demanda',
    'infrastructure.electricalTitle': 'Capacidad Eléctrica',
    'infrastructure.electrical1': 'Subestación redundante de 7 MVA',
    'infrastructure.electrical2': 'Línea de media tensión 23 KV',
    'infrastructure.electrical3': '140 KVA por hectárea disponibles',
    'infrastructure.electrical4': 'Alumbrado público LED',
    'infrastructure.waterTitle': 'Agua',
    'infrastructure.water1': 'Dos pozos de agua',
    'infrastructure.water2': 'Acuífero con disponibilidad para usuarios de alta demanda',
    'infrastructure.water3': 'Planta de tratamiento de aguas residuales MBBR (90 m³/día)',
    'infrastructure.servicesTitle': 'Servicios Adicionales',
    'infrastructure.services1': 'Conducciones para voz y datos',
    'infrastructure.services2': 'Gas natural disponible',
    'infrastructure.services3': 'Edificio de administración del parque y áreas de servicio',
    'infrastructure.services4': 'Estación de combustible en sitio planificada',
    'bts.title': 'Terreno Disponible para Proyectos Build-to-Suit',
    'bts.subtitle': 'Además de los edificios existentes, CLJ ofrece soluciones integrales de terreno',
    'bts.landAlt': 'Vista aérea del terreno industrial CLJ',
    'bts.availableNow': 'Disponible Ahora',
    'bts.feature1Title': '30+ hectáreas',
    'bts.feature1Desc': 'Totalmente servidas con infraestructura en límite de lote',
    'bts.feature2Title': '23+ hectáreas',
    'bts.feature2Desc': 'Hectáreas de terreno industrial de reserva adicional',
    'bts.projectCapabilities': 'Capacidades del Proyecto',
    'bts.projectDesc': 'Adecuado para proyectos BTS desde 10,000 m² hasta más de 100,000 m², adaptados a las necesidades exactas del usuario.',
    'locationInfo.facilityName': 'Ubicación 2',
    'locationInfo.street': 'Manzana 057',
    'locationInfo.city': 'Jilotepec de Molina Enríquez',
    'locationInfo.state': 'Edo. de México',
    'locationInfo.postalCode': 'C.P. 54250',
    'locationInfo.warehouseAddress': 'Dirección del Almacén',
    'locationInfo.viewOnMaps': 'Ver en Google Maps',
    'locationInfo.mapTitle': 'Mapa de ubicación del almacén',
    'idealFor.title': 'Ideal Para',
    'idealFor.op1Title': 'Centros de Distribución Nacional y Regional',
    'idealFor.op1Desc': 'Operaciones a gran escala que requieren coordinación logística eficiente',
    'idealFor.op2Title': 'Comercio Electrónico y Cumplimiento Retail',
    'idealFor.op2Desc': 'Procesamiento de pedidos y gestión de entregas a ritmo acelerado',
    'idealFor.op3Title': 'Proveedores de Logística 3PL',
    'idealFor.op3Desc': 'Servicios de almacén y transporte multi-cliente',
    'idealFor.op4Title': 'Manufactura y Operaciones de Ensamblaje',
    'idealFor.op4Desc': 'Instalaciones de producción con necesidades complejas de cadena de suministro',
    'idealFor.op5Title': 'Usuarios de Servicios de Alta Demanda',
    'idealFor.op5Desc': 'Operaciones que requieren energía y recursos consistentes',
    'idealFor.op6Title': 'Operaciones de Cadena de Suministro Corporativa',
    'idealFor.op6Desc': 'Gestión logística y de distribución a nivel empresarial',
  },
};

export function useWarehouseConfig() {
  const { locale } = useLanguage();
  return useMemo(
    () =>
      locale === 'es'
        ? { ...warehouseConfig, ...spanishTranslations }
        : warehouseConfig,
    [locale],
  );
}

export function useUITranslations() {
  const { locale } = useLanguage();
  return useCallback(
    (key: string): string =>
      uiTranslations[locale]?.[key] ?? uiTranslations.en[key] ?? key,
    [locale],
  );
}

